spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/int1433
    username: int1433
    password: int1433_dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

int1433:
  challenge:
    tcp-port-min: 19310
    tcp-port-max: 19330
    udp-port-min: 19410
    udp-port-max: 19430
    rmi-registry-port: 19500
