spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/int1433
    username: int1433
    password: int1433_dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
